import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url); const { chromium }=require('playwright');

const root=path.resolve(import.meta.dirname,'..'); const port=4174;
const types={'.html':'text/html','.css':'text/css','.js':'text/javascript','.png':'image/png','.webp':'image/webp','.ico':'image/x-icon','.xml':'application/xml'};
const server=http.createServer((req,res)=>{let pathname=decodeURIComponent(new URL(req.url,`http://127.0.0.1:${port}`).pathname); let file=path.join(root,pathname); if(pathname.endsWith('/')) file=path.join(file,'index.html'); if(!path.extname(file)&&fs.existsSync(file)&&fs.statSync(file).isDirectory()) file=path.join(file,'index.html'); if(!fs.existsSync(file)){file=path.join(root,'404.html');res.statusCode=404} res.setHeader('content-type',types[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res)});
await new Promise(r=>server.listen(port,'127.0.0.1',r));
const xml=fs.readFileSync(path.join(root,'sitemap.xml'),'utf8'); const paths=[...xml.matchAll(/<loc>https:\/\/raptorconsultinggroup\.com([^<]*)<\/loc>/g)].map(x=>x[1]);
const browser=await chromium.launch({headless:true}); const errors=[]; const results=[]; const shotDir=path.join(root,'qa-screenshots'); fs.rmSync(shotDir,{recursive:true,force:true}); fs.mkdirSync(shotDir);
for(const route of paths){
 const page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'}); const consoleErrors=[]; page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())}); page.on('pageerror',e=>consoleErrors.push(e.message));
 await page.goto(`http://127.0.0.1:${port}${route}`,{waitUntil:'load'});
 const audit=await page.evaluate(()=>{const named=e=>((e.getAttribute('aria-label')||e.innerText||e.getAttribute('alt')||'').trim().length>0);const ids=[...document.querySelectorAll('[id]')].map(x=>x.id);return {h1:document.querySelectorAll('h1').length,lang:document.documentElement.lang,title:document.title,main:document.querySelectorAll('main').length,unlabeledNav:[...document.querySelectorAll('nav')].filter(x=>!x.getAttribute('aria-label')).length,missingAlt:document.querySelectorAll('img:not([alt])').length,unnamedButtons:[...document.querySelectorAll('button')].filter(x=>!named(x)).length,unnamedLinks:[...document.querySelectorAll('a[href]')].filter(x=>!named(x)).length,duplicateIds:[...new Set(ids.filter((x,i)=>ids.indexOf(x)!==i))],overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth,skip:!!document.querySelector('a.skip-link[href="#main-content"]'),reduced:getComputedStyle(document.documentElement).scrollBehavior}});
 if(audit.h1!==1||audit.main!==1||!audit.lang||!audit.title||audit.unlabeledNav||audit.missingAlt||audit.unnamedButtons||audit.unnamedLinks||audit.duplicateIds.length||audit.overflow>1||!audit.skip||consoleErrors.length) errors.push({route,audit,consoleErrors}); results.push({route,audit,consoleErrors}); await page.close();
}
const reps=['/','/services/search-systems/','/services/search-systems/technical-seo/system-audit/','/work/','/about/ricardo-canilao/','/insights/','/contact/']; const widths=[['desktop',1440,1000],['tablet',1024,900],['mobile',390,844]];
for(const route of reps) for(const [label,width,height] of widths){const page=await browser.newPage({viewport:{width,height}});await page.goto(`http://127.0.0.1:${port}${route}`,{waitUntil:'load'});const name=(route==='/'?'home':route.split('/').filter(Boolean).join('-'));await page.screenshot({path:path.join(shotDir,`${name}-${label}.png`),fullPage:true});await page.close()}
const interaction=await browser.newPage({viewport:{width:390,height:844}});await interaction.goto(`http://127.0.0.1:${port}/`,{waitUntil:'load'});const toggle=interaction.locator('.menu-toggle');await toggle.click();if(await toggle.getAttribute('aria-expanded')!=='true')errors.push({interaction:'menu did not open'});await interaction.keyboard.press('Escape');if(await toggle.getAttribute('aria-expanded')!=='false')errors.push({interaction:'Escape did not close menu'});if(!(await toggle.evaluate(e=>e===document.activeElement)))errors.push({interaction:'focus did not return to menu toggle'});await toggle.click();const details=interaction.locator('.nav-services');await details.locator('summary').click();if(!(await details.evaluate(e=>e.open)))errors.push({interaction:'Services disclosure did not open'});await interaction.close();
await browser.close();server.close();
const report={pages:paths.length,representativeScreenshots:reps.length*widths.length,errors,results};fs.writeFileSync(path.join(root,'qa-responsive-accessibility.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({pages:paths.length,screenshots:reps.length*widths.length,errorCount:errors.length,errors:errors.slice(0,20)},null,2));process.exitCode=errors.length?1:0;
